//
//  ViewController.m
//  CameraApp-AVFoundation
//
//  Created by Karthick C on 08/01/18.
//  Copyright © 2018 Karthick C. All rights reserved.
//

#import "ViewController.h"

@interface ViewController ()
@property (nonatomic,weak) IBOutlet UIButton *captureButton;

///Displays a preview of the video output generated by the device's cameras.
@property (nonatomic,weak) IBOutlet UIView *capturePreviewView;

//Allows the user to put the camera in photo mode.
@property (nonatomic,weak) IBOutlet UIButton *photoModeButton;
@property (nonatomic,weak) IBOutlet UIButton *toggleCameraButton;
@property (nonatomic,weak) IBOutlet UIButton *toggleFlashButton;

//Allows the user to put the camera in video mode.
@property (nonatomic,weak) IBOutlet UIButton *videoModeButton;
@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    [self styleCaptureButton];
}

- (void) styleCaptureButton {
    self.captureButton.layer.borderColor = [[UIColor blackColor] CGColor];
    self.captureButton.layer.borderWidth = 2;
    self.captureButton.layer.cornerRadius = MIN(self.captureButton.frame.size.width, self.captureButton.frame.size.height)/2;
}

@end
